// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewCoEF;

namespace NewCoEF.Migrations
{
    [DbContext(typeof(NewCoEFDbContext))]
    [Migration("20220214073405_Initialdatabase")]
    partial class Initialdatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NewCoEF.Shared.Areas.PersonalData.Models.Country", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(22)")
                        .HasMaxLength(22);

                    b.HasKey("ID");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("NewCoEF.Shared.Areas.PersonalData.Models.County", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("Counties");
                });

            modelBuilder.Entity("NewCoEF.Shared.Areas.PersonalData.Models.Customer", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CountryRefID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CountyRefID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PostCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VATRegistrationCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CountryRefID");

                    b.HasIndex("CountyRefID");

                    b.HasIndex("Name")
                        .HasName("Customer_Name_Index");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("NewCoEF.Shared.Areas.PersonalData.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal>("Inventory")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("No")
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnName("Unit Price")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .HasName("Item Description Index");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("NewCoEF.Areas.Sales.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CustomerRefID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("No")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("CustomerRefID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("NewCoEF.Areas.Sales.Models.OrderLine", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ItemRefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("LineAmount")
                        .HasColumnName("Line Amount")
                        .HasColumnType("money");

                    b.Property<int>("LineNo")
                        .HasColumnName("Line No")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnName("Unit Price")
                        .HasColumnType("money");

                    b.HasKey("OrderId", "Id");

                    b.HasIndex("ItemRefId");

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("NewCoEF.Shared.Areas.PersonalData.Models.Customer", b =>
                {
                    b.HasOne("NewCoEF.Shared.Areas.PersonalData.Models.Country", "CountryRef")
                        .WithMany()
                        .HasForeignKey("CountryRefID");

                    b.HasOne("NewCoEF.Shared.Areas.PersonalData.Models.County", "CountyRef")
                        .WithMany()
                        .HasForeignKey("CountyRefID");
                });

            modelBuilder.Entity("NewCoEF.Areas.Sales.Models.Order", b =>
                {
                    b.HasOne("NewCoEF.Shared.Areas.PersonalData.Models.Customer", "CustomerRef")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerRefID");
                });

            modelBuilder.Entity("NewCoEF.Areas.Sales.Models.OrderLine", b =>
                {
                    b.HasOne("NewCoEF.Shared.Areas.PersonalData.Models.Item", "ItemRef")
                        .WithMany()
                        .HasForeignKey("ItemRefId");

                    b.HasOne("NewCoEF.Areas.Sales.Models.Order", "OrderRef")
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
